# Generated by Django 4.0 on 2022-01-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEnt', models.CharField(max_length=50)),
                ('RaisonSociale', models.CharField(max_length=50)),
                ('Adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NbEtudEq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FicheEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoteRapport', models.FloatField()),
                ('NoteRéalisation', models.FloatField()),
                ('NoteSoutenance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NbPages', models.IntegerField()),
                ('Fichier', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TypeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntituléTS', models.CharField(max_length=50)),
                ('Période', models.CharField(max_length=100)),
                ('DuréeTS', models.CharField(max_length=50)),
                ('NbEtudiants', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SujetPFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntituléS', models.CharField(max_length=50)),
                ('Résumé', models.TextField()),
                ('Plan', models.TextField()),
                ('NumEnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Durée', models.IntegerField()),
                ('DateDeb', models.DateField()),
                ('Fiche_Eval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.ficheevaluation')),
                ('NumEnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.entreprise')),
                ('Rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.rapport')),
                ('Sujet_pfe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.sujetpfe')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.typestage')),
            ],
        ),
        migrations.CreateModel(
            name='Promoteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomP', models.CharField(max_length=40)),
                ('PrénomP', models.CharField(max_length=50)),
                ('Profession', models.CharField(max_length=50)),
                ('NumeroP', models.CharField(max_length=10)),
                ('EmailP', models.EmailField(max_length=254)),
                ('NumEnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.entreprise')),
                ('NumJury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.jury')),
                ('Stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.stage')),
            ],
        ),
        migrations.AddField(
            model_name='ficheevaluation',
            name='Jury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.jury'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('Matricule', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=40)),
                ('Prénom', models.CharField(max_length=50)),
                ('Numero', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('DateNaiss', models.DateField()),
                ('AnnéeEtude', models.IntegerField()),
                ('Spécialité', models.CharField(max_length=30)),
                ('Equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='Stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.stage'),
        ),
        migrations.CreateModel(
            name='Encadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomE', models.CharField(max_length=40)),
                ('PrénomE', models.CharField(max_length=50)),
                ('Domaine', models.CharField(max_length=50)),
                ('NumeroE', models.CharField(max_length=10)),
                ('EmailE', models.EmailField(max_length=254)),
                ('NumJury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.jury')),
                ('Stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.stage')),
            ],
        ),
    ]
