# Generated by Django 4.0 on 2022-01-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='Email',
            new_name='EmailE',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='Nom',
            new_name='NomE',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='Numero',
            new_name='NumeroE',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='Prénom',
            new_name='PrénomE',
        ),
        migrations.AddField(
            model_name='jury',
            name='session',
            field=models.CharField(default='MM-AAAA', max_length=7),
        ),
        migrations.AlterField(
            model_name='jury',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
