# Generated by Django 4.0 on 2022-01-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
