# Generated by Django 4.0 on 2022-01-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_delete_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Matricule',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
