# Generated by Django 4.0 on 2022-01-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_remove_equipe_nbetudeq'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='Etudiants',
            field=models.ManyToManyField(to='Gestion.Etudiant'),
        ),
    ]
