# Generated by Django 4.0 on 2022-01-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_equipe_etudiants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='Equipe',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='Equipes',
            field=models.ManyToManyField(to='Gestion.Equipe'),
        ),
    ]
