# Generated by Django 4.0 on 2022-01-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0009_remove_etudiant_equipe_etudiant_equipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='Etudiants',
        ),
    ]
