# Generated by Django 4.0 on 2022-01-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0011_remove_etudiant_equipes_etudiant_equipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='AnnéeEtude',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='Matricule',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
