# Generated by Django 4.0 on 2022-01-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0013_encadreur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujetpfe',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
