# Generated by Django 4.0 on 2022-01-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0015_alter_etudiant_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Rapport',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rapport',
        ),
    ]
