# Generated by Django 4.0 on 2022-01-29 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0019_rename_encadreur_encadrant_stage_encadrant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encadrant',
            name='image',
            field=models.ImageField(default='etudiants/images/noimg.png', upload_to='encadrants/images/'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='image',
            field=models.ImageField(default='etudiants/images/noimg.png', upload_to='etudiants/images/'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='Encadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.encadrant'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='Promoteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gestion.promoteur'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='Rapport',
            field=models.FileField(null=True, upload_to='rapports/'),
        ),
    ]
